# Generated by Django 4.0.6 on 2022-08-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.TextField(default=123, max_length=140),
            preserve_default=False,
        ),
    ]
