# Generated by Django 4.0.6 on 2022-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.TextField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, null=True),
        ),
    ]
