# Generated by Django 4.0.6 on 2022-09-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_height_alter_profile_introduce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bottom_size',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='top_size',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
