# Generated by Django 4.0.6 on 2022-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_bottom_size_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(max_length=3),
        ),
    ]
