# Generated by Django 4.0.6 on 2022-09-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profileimage_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profile_image',
            new_name='photo',
        ),
    ]
