# Generated by Django 4.0.6 on 2022-09-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_profile_image_profileimage_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='profile',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
