# Generated by Django 4.0.6 on 2022-08-10 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_post'),
        ),
        migrations.AlterField(
            model_name='stylephoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_post'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_sets', to='item_post.item')),
                ('like_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
