# Generated by Django 4.0.6 on 2022-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
