# Generated by Django 4.0.6 on 2022-08-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_post', '0002_alter_photo_photo_alter_stylephoto_photo_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
