# Generated by Django 4.0.6 on 2022-08-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_post', '0002_item_sold_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wear_count',
            field=models.CharField(max_length=20),
        ),
    ]
