# Generated by Django 4.0.6 on 2022-08-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_post', '0003_alter_item_wear_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='wear_count',
            new_name='condition',
        ),
    ]
