# Generated by Django 4.0.6 on 2022-08-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_post', '0004_rename_wear_count_item_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='feature',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_defect',
        ),
    ]
