# Generated by Django 4.0.6 on 2022-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_post', '0005_rename_description_item_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='big_category',
            field=models.CharField(max_length=20),
        ),
    ]
