# Generated by Django 4.0.6 on 2022-09-05 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_post', '0006_alter_category_big_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchaser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_buy_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
