# Generated by Django 4.0.6 on 2022-09-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_post', '0007_item_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationset',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_item_sets', to='item_post.item'),
        ),
    ]
