# Generated by Django 4.0.6 on 2022-09-07 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_post', '0007_item_purchaser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied', models.CharField(choices=[('SF', 'Satisfaction'), ('US', 'Unsatisfaction')], default=0, max_length=2)),
                ('review', models.TextField(blank=True, max_length=140, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_target', to='item_post.item')),
            ],
        ),
    ]
