# Generated by Django 4.0.6 on 2022-09-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='satisfied',
            field=models.CharField(choices=[('SF', 'Satisfaction'), ('US', 'Unsatisfaction')], default=None, max_length=2),
        ),
    ]
