# Generated by Django 4.0.6 on 2022-08-16 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_post', '0002_item_height_item_weight'),
        ('relationship', '0002_rename_followed_id_follow_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likeitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeitem', to='item_post.item'),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StyleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeStyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeStyle', to='item_post.stylephoto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
