# Generated by Django 4.0.6 on 2022-08-22 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_post', '0002_item_height_item_weight'),
        ('relationship', '0003_alter_like_likeitem_alter_like_likeuser_stylelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeitem_sets', to='item_post.item'),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeitem_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StyleLike',
        ),
    ]
